project:
  type: website
  output-dir: docs

website:
  title: "Melissa Knox"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - teaching.qmd
      - outreach.qmd
      - pnwld.qmd
      - cv.qmd


format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

