project:
  type: website
  output-dir: docs

render:
    - "*.qmd"
    
website:
  title: "Melissa Knox"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - papers.qmd
      - outreach.qmd
      - href: pnwld.qmd
        text: PNWLD
      - href: teaching.qmd
        text: Teaching
      
   

  
  page-footer: 
    left: Copyright 2024, Melissa Knox
    right: Made with RStudio and Quarto
format: 
  html:
    theme: yeti
    css: styles.css
    toc: false
    page-layout: full

editor: visual




