---
title: "For Students"
toc: TRUE
---

This page is meant to provide resources for students and to answer frequently asked questions. You can navigate the page with the links above. Would you like to see more resources here? Email me!

### Recommendation Letter Requests

------------------------------------------------------------------------

If you are considering requesting that I write you a recommendation letter, please read the guidelines for letter requests below.

#### Minimum Requirements

------------------------------------------------------------------------

-   You took a 400-level class (or two) from me and performed in the top 10% of your class (\~3.7 grade).

    -   It's additionally helpful if you spent time in my office hours discussing anything other than your recommendation letter.

    -   You exhibited integrity, motivation, and maturity in my class, or

<!-- -->

-   You did an independent study or honors thesis with me, or

<!-- -->

-   You worked for me or got to know me well in some other capacity.

#### Requesting a Letter

------------------------------------------------------------------------

If you meet one of the requirements above, please send me an email with your request (and telling me how you meet the criteria above) before October 1. I will let you know by October 15, once I have a sense of how many requests I have received.

Whether or not I am able to write you a letter, good luck with the application process!

### Data Resources for Students

------------------------------------------------------------------------

#### Econ 448

Students in Econ 448 typically use data from [The Human Mortality Database](mortality.org) and [IPUMS International](https://international.ipums.org/international/){.uri}. These are both wonderful sources of data for demographic and household-level studies. Students in Econ 448 are required to make a free account at these websites and agree to all rules and restrictions surrounding the use of the data. Please see [class GitHub repository](https://github.com/melishka/Econ_448_DevoPop) for more information about joining the IPUMS class account and data analysis.

#### Other Sources for International/Household Data Projects

[IPUMS](https://www.ipums.org/)- Census and survey data from around the world. Includes access to the Demographic and Health Surveys from the DHS Program. Various levels of approval required, depending on the dataset.

[Worldbank Living Standards Measurement Surveys (LSMS)](https://www.worldbank.org/en/programs/lsms) - Household surveys in many countries and many years.

[IHME Global Health Data](https://ghdx.healthdata.org/) - Comprehensive health data (surveys and vital statistics for many countries).

[IMF Data Library](data.imf.org) - Time series data on economic indicators (good source of macro data sets)

[ICPSR](https://www.icpsr.umich.edu/web/pages/) - University of Michigan data repository with a variety of data sources. Your UW email should get you access, but you will need to get approved.

[UW Databases](https://guides.lib.uw.edu/research/business/databases) - Includes Economist Intelligence Unit (EIU) with good background data on most countries. Note: Need UW login to access.

#### Data Analysis Tips

I am mainly a Stata user, but I make students in Econ 448 learn and use R. Why? Well, it's free, it's more flexible than Stata, it's more widely used than Stata, and it integrates well with other programs you might want to use like Python or SQL. [Need more reasons to learn R?](https://www.r-bloggers.com/2014/03/why-use-r-five-reasons)

However, R and Stata are just tools. In order to use them to produce the output you desire, I highly recommend that you focus on two things:

1.  The structure of your data, both how it is arranged and how you are storing it/importing it into your statistical program. Understanding R packages like [tidyr](https://vita.had.co.nz/papers/tidy-data.pdf) is a great place to start, but you will probably also need some basic understanding of linear algebra to ensure that you process your data correctly.
2.  The source of your data, including the codebook, data dictionary, and any survey questions (if you have access). This includes understanding how survey respondents (or whatever entity forms the primary unit of analysis in your data) were chosen.Once you understand these things about your data, figuring out the correct syntax and programming steps is often just a matter of consulting resources like stack exchange. However, if you don't understand them, it's pretty hard to trust your results!
