---
title: "PNW Labor Day"
permalink: /PNWLD/
redirect_from:
  - /pnwld
listing:
  id: past-conferences
  contents: PNWLD/*
  sort: "title"
  sort-ui: false
  type: table
  fields: [title]

---
Email me or pnwldorganize at gmail dot com to be added to the email list. Call for papers coming in Summer 2024!


#### 6th Annual Pacific Northwest Labor Day Workshop
September 15, 2023\
University of Washington\
Room 410, Savery Hall\
Seattle, WA\

(Zoom link available with registration)


9:30 – 9:45: Coffee and Pastries

9:50: Opening Remarks

10:00 – 10:50: Melissa Knox, Jessica Jones-Smith, Jessica Godwin, and Steve Mooney. “Using Electronic Health Records to Estimate the Association Between Seattle’s Sweetened Beverage Tax and Weight Gain Trajectories in Adults and Children”

11:00 – 11:50: Cheng Chen and Lucy Hong. "Evaluating E-cigarette Sales Restrictions: Insights into Consumption and Substitution Behavior"

12:00 – 12:50: Katie Bollman, Judhajit Chakraborty, Leah Lakdawala, and Eduardo Nakasone. “Frosty Climate, Icy Relationships: Frosts and Intimate Partner Violence in Rural Peru”

1:00 – 2:00 Lunch 

2:00 – 2:50: Rafiuddin Najam and Paul Thompson. “Impacts of the Four-Day School Week on Juvenile Crime” 

3:00 – 3:50: Todd Pugatch and Paul Thompson. “Excellence for all? University honors programs and human capital formation”

4:00: Adjourn 

---

::: {#sample-listings}
:::